apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy/acorn-scratch.yaml
configurations:
- deploy/kustomizeconfig/acorn_app.yaml
images:
- digest: sha256:e1ce28637b0cf56e7e1a396ade75a70ae3fffbc7
  name: dukeman/acorn-scratch
  newName: docker.io/dukeman/acorn-scratch
