apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy/acorn-scratch.yaml
configurations:
- deploy/kustomizeconfig/acorn_app.yaml
images:
- name: docker.io/dukeman/acorn-scratch
  newTag: v0.1.0
