apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acorn-scratch-cert
  namespace: acorn
spec:
  dnsNames:
  - scratch.leetserve.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: awesome-acorn-tls-secret
