apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: leetxor-acorn-cert
spec:
  dnsNames:
  - acorn.leetserve.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: awesome-acorn-tls-secret
