# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags: ["*"]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: tenhaus/get-release-or-tag@v2
      id: tag
    - uses: acorn-io/actions-setup@v1
    - uses: acorn-io/actions-login@v1
      with:
        registry: docker.io
        username: dukeman
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - run: |
        acorn build -p linux/amd64,linux/arm64 -t docker.io/dukeman/acorn-scratch:${{ steps.tag.outputs.tag }} .
        acorn push docker.io/dukeman/acorn-scratch:${{ steps.tag.outputs.tag }}
